# Define stages
stages:
  - build
  - deploy

# Define job templates
.template:
  image: node:lts

# install package for web app
app-install:
  stage: build
  extends: .template
  script:
   - cd web-app
   - npm install
  artifacts:
    paths:
      - web-app/node_modules 


# build web app
app-build:
  stage: build
  extends: .template
  script:
    - cd web-app 
    - npm run build
  needs: ["app-install"]
  allow_failure:
    exit_codes:
      - 1
  artifacts:
    paths:
      - web-app/dist

deploy:
  stage: deploy
  image: php:latest
  script:
    - apt-get update && apt-get install -y unzip git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer 
    - cd backend/
    - composer install
    # Add your deployment steps here

