services:
  - name: mongo:6.0
    alias: mongodb


# Define stages
stages:
  - build 

# Define job templates
.template:
  image: node:lts

# install package for web app
app-install:
  stage: build
  extends: .template
  script:
   - cd web-app
   - npm install
  artifacts:
    paths:
      - web-app/node_modules 


# build web app
app-build:
  stage: build
  extends: .template
  script:
    - cd web-app 
    - npm run build
  needs: ["app-install"]
  allow_failure:
    exit_codes:
      - 1
  artifacts:
    paths:
      - web-app/dist


backend-install:
  stage: build
  extends: .template
  script:
   - cd backend
   - npm install
  artifacts:
    paths:
      - backend/node_modules
    expire_in: 1 day

backend-linting:
  stage: build
  extends: .template
  before_script:
    - cd backend
  script:
    - npm run build:lint
  needs: ["back-install"]
  allow_failure:
    exit_codes:
      - 1

backend-compile:
  stage: build
  extends: .template
  before_script:
    - cd backend
  script:
    - npm run build:tsc
  needs: ["backend-install", "backend-linting"]
  artifacts:
    paths:
      - backend

    
    
 


