# Define stages
stages:
  - build
  - deploy

# Define job templates
.template:
  image: node:lts

# Define jobs
build:
  stage: build
  extends: .template
  script:
    - cd web-app 
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  image: php:latest
  script:
    - cd backend/
    - composer install
    # Add your deployment steps here

